apiVersion: v1
kind: ConfigMap
metadata:
  name: data-store-env
data:
  folder: "story" # This is the environment variable that will be used in the app.js file to read the story folder
  # key : value # This is how you can add more environment variables
