apiVersion: v1
kind: PersistentVolume # This is a Persistent Volume, which is a piece of storage in the cluster that has been provisioned by an administrator or dynamically provisioned using Storage Classes.
metadata:
  name: host-pv # Name of the Persistent Volume
spec:
  capacity:
    storage: 1Gi # This is the size of the volume
  volumeMode: Filesystem # there is file and block mode, file is default
  storageClassName: standard # This is the name of the Storage Class that this Persistent Volume belongs to
  accessModes:
    - ReadWriteOnce # This means the volume can be mounted as read-write by a single node
    # - ReadOnlyMany # This means the volume can be mounted as read-only by many nodes
    # - ReadWriteMany # This means the volume can be mounted as read-write by many nodes
  hostPath:
    path: /data
    type: DirectoryOrCreate # This will create the directory if it does not exist
