apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv # This is the name of the Persistent Volume we created
  accessModes:
    - ReadWriteOnce # This means the volume can be mounted as read-write by a single node
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi # This is the size of the volume

