apiVersion: v1
kind: Service
metadata:
  name: backend # Name of the service, it can be anything
  labels:
    group: example # Label to identify the service, it can be anything
spec:
  selector: # This is used to identify the pods that are part of this service
    app: second-app # Label to identify the pod it can app or anything else
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
    # - protocol: "TCP"
    #   port: 443
    #   targetPort: 8443
  type: LoadBalancer
